### ISSUE TITLE
Mojave 10.14.2 - script failed install

### ISSUE THREAD

**Issue by kormoranmen** [syscl/M3800#106]
Hello,

first thanks for a great work. I used your script to install Mojave in 10.14.2.
Install was successful, but when i use a script there is not working.

Script will run, patch DSDT, copy and compile it. SSDT also ok. But video card not working (show only 31MB) audio also not working. Wifi, BT works OOTB. 

I use last clover, also tried to update Lilu, whatevergreen but no success.

Maybe can you help ;-)

Best regards.

**Comment by froggr** [comment]
Video card issues for me however same approach as in #105 solved for me. 

Working: 
* Wifi (OOTB) 
* touchpad multitouch

Not working:
 * BT
* Sound (AppleALC)
* sleep/wake
* touch screen
* screen brightness

**Comment by GuillaumeHullin** [comment]
Same issues here.
@froggr do you mean that you found a solution in the thread you linked? If yes, do you mind doing a short Japanese translation :/ Google Translate is that great on it.

**Comment by froggr** [comment]
私は翻訳してうれしいです。 Google翻訳でこれを理解しにくければ、私は謝罪します。

そこで私は1920 x 1080で妥当なグラフィックパフォーマンスを得るために以下の手順を完了しました。

* EFIをマウントする
* クローバー設定で以下の設定を変更してください。
  * `ACPI`  - > `SSDT`
    * DropOEMをfalseに設定します。
  * `ACPI`  - > `fixes`
    * FixDisplayをtrueにする
    * FixIntelGfxをtrueにする

Clover config.plistファイルの編集に慣れていない場合は、Clover Configuratorのようなアプリケーションを使用できます。

私はそれがあなたに合っていればいいと思う。

**Comment by GuillaumeHullin** [comment]
Thanks @froggr, but I meant Japanese to English ahaha the threadyou linked was in Japanese. However "your" Japanese was Google translatable ;) so I'm gonna try that.

**Comment by GuillaumeHullin** [comment]
@kormoranmen I had the same problem than you and the explanation of @froggr fixed the graphic card issues (and the scaling of the screen).
Now its only 
    Bluetooth
    Sound
   Sleep 
   Touch screen (working on that)
   Screen brightness

**Comment by GuillaumeHullin** [comment]
Ok I managed to get the touchscreen working on my M3800 with Mojave.

First you have to find the correct touchscreen model... Open System Information and I found the touchscreen in Hardware > USB
Synaptics Large Touch Screen
  Product ID:	0x0ac3
  Vendor ID:	0x06cb  (Synaptics Inc.)
  Version:	0.02
  Speed:	Up to 12Mb/sec
  Manufacturer:	SYNAPTICS
  Location ID:	0x14500000 / 7
  Current Available (mA):	500
  Current Required (mA):	144
  Extra Operating Current (mA):	0
  Built-In:	Yes 

Go to and download the right driver for MacOS:
https://www.touch-base.com/download.asp

(this is where I got confused the first time because if I used the option "Help identifying controller or device?" then it would advised me "Quanta Computer, Dual, USB")

Install the driver on you macOS and then you need to adjust one more thing for the click to work. 
Go to System Preferences > Security and Privacy > Privacy > Accessibility 
Add the App "aideamon" (located in Library⁩ ▸ ⁨Application Support⁩ ▸ ⁨UPDD⁩). It might propose already before to add the Unix executable called aideamon but you want the App package, not just the exe.

Et voila, after calibration I could use my touchscreen, however there is only one thing I want to fix on that is the scrolling!

Note that the driver is an evaluation and a license cost more than 100 EUR.

**Comment by GuillaumeHullin** [comment]
> Et voila, after calibration I could use my touchscreen, however there is only one thing I want to fix on that is the scrolling!

http://touch-base.com/documentation/MacOSXPlatformNotesV5.htm
Multi-touch gestures are not available in the evaluation version as the gesture software checks that a licensed version is installed.

**Comment by kormoranmen** [comment]
Hey guys.

Please test following zip:
https://www.web-master.pl/m3800/m3800_mojave.zip

this is my own-generated version, based on my 10.13.6 High Serra version what i use from long time.
I create a clean clover boot, copy this package. The installer turns on, as well as the system with this package.

Should work graphics, audio, brightness, wi-fi, bluetooth, sleep, wake. After copy please clean cache kext -> `sudo kextcache -i /`

I knew this touch screen driver but don;t use it - 100 EUR is a lot of cash ;-(.

One not working think is HDMI and DP (not tested). HDMI - when connect display system hangs and restart. Maybe someone fix it.

Let me know if my package works for you.
My config -> 4702HQ, 16GB RAM, UHD 3200x1800, SSD + HDD.

**Comment by froggr** [comment]
LOL! Sorry about that @GuillaumeHullin. Too funny.

@kormoranmen I'll take a look

**Comment by froggr** [comment]
@kormoranmen sound and wifi work but i had to do the above stated change for intel graphics. No brightness, sleep/wake, bluetooth.

**Comment by syscl** [comment]
Actually, the bug is from Clover's change of ACPI, I have to tune it and find a work around.

**Comment by Bitbanger1900** [comment]
Hi,

I run a Dell M3800 with Mojave (10.14.2) and an USB Dock (D3100). Actually i run three screens pretty good!.
The only problem i have is also with the graphics. 

In three-screen mode i have DeviceID: 0x0416, Revision ID: 0x006 with 3200x1800 QHD+ but with 21MB VRAM (Total) and problems with the graphics (when is say it correct, no GFX accel).

When i change it with clover to Drop OEM, FixIntelGfx and FixDisplay and inject IntelGFX 0x04128086 with ig-platform-id 0x0a2e0008 the screens on my dock run perfect without problems but the laptop screen is on 3200x1800 without "desktop" hanging with the apple and progressbar underneath it.

What is the correct setting in clover for the intelGFX? When i install the provided config.plist i have the 0x0416 with 21MB VRAM.

Clover version 4813 by the way.

Update:
I entered in the clover boot options 0x04128086 and 0x0a2e0008 and now i have three screens working and the display of the laptop is now running 1600 x 900?? But all perfect.... Never touch a running system?

Kind Regards

**Comment by syscl** [comment]
Hi all, the deploy script will be no more needed because I am working on dynamic patching ACPI tables without dump ACPI with the latest Clover. 

Here's the things currently working:
- Graphics card (with HDMI supported as well!)
- Brightness
- Power Management with XCPM
- USB ports
- Webcam
- Touchpad with precision multiple touch with 3finger drag and tap/look up!

The only thing not work until now is the ALC668 with ACPI hot patch, I will figure out a workaround today!

thank you 
syscl

**Comment by syscl** [comment]
Audio issue has been solved as well. But using hot patch I am now facing a new issue: randomly kernel panic during boot. That's annoying, because pervious old static ACPI patching using deploy has 0 issues! 

I am still investigating what's wrong with the dynamic ACPI patching method. In short, the dynamic ACPI patching method cannot do as much as static ACPI patching as we did before, but RehabMan has messed up the whole ACPI function in Clover, which I have to figure out a simple work around.

**Comment by froggr** [comment]
@syscl this sounds great. Was reading about some of this on TonyMac. I'm happy to help, test, etc. just let me know.

**Comment by syscl** [comment]
There’s something wrong with dynamic patching right now, cannot resolve several compile issues like zeros and MDBG. And we have to override some properties within the DSDT otherwise the old methods will interfere the system’s behavior. What I would recommend is a minimal static ACPI patching with hot patching.

**Comment by kormoranmen** [comment]
Can you provide a configuration and other files to test it?

**Comment by GuillaumeHullin** [comment]
@syscl almost work for the audio... I got static in the headphone but I can hear in the background the audio output (behind all the static noise)

**Comment by syscl** [comment]
Here you go, please test and let me know the result.
Steps:
- Backup your clover
- Replace the ```config.plist``` and ```ACPI/patched``` with the files I provided.
- Reboot and see the change. 
[EFI-config.zip](https://github.com/syscl/M3800/files/2719108/EFI-config.zip)

**Comment by syscl** [comment]
In short, the config works on my M3800 QHD+, it should work on other platform as well. But the problem is still the ACPI patching is incomplete with only Clover hot patching. 

Things we have to consider for ACPI patching is:
- Proper ACPI code such that there won't be improper interrupts being generated that will cause the system unstable
- Remove or override properties of some devices such as ```HDEF```, ```PPMC```, ```PMCR``` and ```ALS0```, ...
- Avoid duplicate devices being injected
- Resolve the common decompile errors, Zeros, MDBG(0) and etc.
- Resolves several warnings 
- ...

Clover hot patching can perform rename and apply limited patches during booting, but still far from the things we can resolve by a simply static ACPI patching using ```deploy.sh```.

**Comment by GuillaumeHullin** [comment]
@syscl, the ACPI and config didn't solve the headphone static.
Can you recommend a good source for learning ACPI patching.... I'm getting confused on how it works and if I could learn it I could maybe be helpful ;)

**Comment by syscl** [comment]
Do you install the CodecCommand as well? I tested on my laptop, no such issue!

**Comment by GuillaumeHullin** [comment]
CodecCommander is ktexts > Other folder
On you last commit I erased my EFI and re-do the all procedure from you git with Deploy.sh

**Comment by GuillaumeHullin** [comment]
But you mean that the lid is also turning off your screen on your M3800?

**Comment by syscl** [comment]
No need deploy if you use the hot patching config.plist I provided in this issue page.

**Comment by GuillaumeHullin** [comment]
Yup sorry, forgot to say that.
I tried today your package, replacing the config and the patched folder... but same result.

**Comment by syscl** [comment]
I have fixed up the decompile issues introduced by ACPI interpreter, and the deploy.sh should works again, please try the latest deploy!

Here's the log running on my laptop
```sh
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble tables.
[  OK  ]  Locate specific ACPI tables..
[ ---> ]  Patching DSDT.dsl
[  OK  ]  Fix PARSEOP_ZERO.
[  OK  ]  Fix ADBG Error.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  7-series/8-series USB.
[  OK  ]  Fix USB _PRW.
[  OK  ]  Acer Aspire E1-571.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  OS Check Fix.
[  OK  ]  Inject Audio Info.
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Remove GLAN device.
[  OK  ]  iGPU TPMX to MEM2.
[  OK  ]  IMTR->TIMR, _T_x->T_x.
[  OK  ]  Insert SLPB.
[  OK  ]  Insert PMCR.
[  OK  ]  Insert PPMC.
[ ---> ]  Patching SSDT-7-DptfTabl.dsl
[  OK  ]  _BST package size.
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-9-SaSsdt.dsl
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Rename HD4600 to Iris Pro.
[  OK  ]  Brightness fix (Haswell).
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Insert HDAU device (c) syscl.
[ ---> ]  Patching SSDT-10-SgPeg.dsl
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-11-OptTabl.dsl
[  OK  ]  Fix up the ACPI interpreter error (aka Store (TCAP, \_PR.CPU0._PTC ()) issue).
[  OK  ]  Remove invalid operands.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Disable Nvidia card (Non-operational in OS X).
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[  OK  ]  Compiling DSDT.
[  OK  ]  Compile DptfTa.
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile SgRef.
[  OK  ]  Compile OptRef.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[ ---> ]  Installing SSDT-m-M3800.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-m-M3800.aml to ./DSDT/compile.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
```

syscl

**Comment by Bitbanger1900** [comment]
Hi,

Just wanted to say that my Dell M3800 is running fine now. Replaced with your config.plist and your ACPI/patched and ran the Deploy.sh script.

Video is running with 0x0412 Rev. 0x0006 with 1536MB on three displays with my USB Dock (1600x900 + (1920x1080)x2).
Audio is also working perfect.

WIFI is working through an external USB adapter. No idea if it works with the internal adapter.

Many thanks for your work! where can i spend you a beer?

Regards,

**Comment by syscl** [comment]
Which WiFi card you have?

**Comment by Bitbanger1900** [comment]
Hi,

Network controller: Intel Corporation Wireless 7260 (rev 6b).

I found another issue with my LCD. When i lock the screen it goes black and never comes back. The external displays are fine. Reboot solves the issue.

**Comment by kormoranmen** [comment]
Intel WiFi is not supported. You must replace it for example to Dell DW1830 to work.

**Comment by Bitbanger1900** [comment]
ah. good to know. 

Thanks!
