### ISSUE TITLE
Black screen after waking up from sleep mode on Mac OS 10.15 Catalina

### ISSUE THREAD

**Issue by andreikr79** [syscl/M3800#121]
After upgrading to 10.15 Catalina everything works except sleep mode. After waking up from sleep mode, the screen does not turn on. Although the keyboard and the os works. 

Problem with bluetooth was resolved here https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/?page=6

**Comment by kormoranmen** [comment]
Hi,
also have this problem, has you any solution for it?

**Comment by kormoranmen** [comment]
Still no solution for it?

**Comment by brucelee2000** [comment]
Same problem here after upgrading to Catalina. Anyone got any idea?

**Comment by brucelee2000** [comment]
> Same problem here after upgrading to Catalina. Anyone got any idea?

I also reported this issue here https://www.insanelymac.com/forum/topic/305488-guide-dell-precision-m3800-3200x1800-qhd-touch-i7-47x2hq-intelhd4600-quadrok1100m-alc668/?page=2

What I found out is that the external screen can wake up with no problem if an external monitor is hooked. However, the laptop screen still stays black. Hopefully someone can shine the light on this issue. Thanks.

**Comment by geminird** [comment]
> > Same problem here after upgrading to Catalina. Anyone got any idea?
> 
> I also reported this issue here https://www.insanelymac.com/forum/topic/305488-guide-dell-precision-m3800-3200x1800-qhd-touch-i7-47x2hq-intelhd4600-quadrok1100m-alc668/?page=2
> 
> What I found out is that the external screen can wake up with no problem if an external monitor is hooked. However, the laptop screen still stays black. Hopefully someone can shine the light on this issue. Thanks.

Same problem

**Comment by syscl** [comment]
@geminird @brucelee2000 @andreikr79 10.15.x supported added.
