### ISSUE TITLE
Deploy.sh 脚本一定要联网才能执行完成么？

### ISSUE THREAD

**Issue by AKA-KC** [syscl/M3800#17]
你以前那个finalstep.sh脚本还用执行么？现在我没联网执行Deploy脚本没反应的.....谢谢....

**Comment by syscl** [comment]
1. 不需要finalstep脚本, 现在也不需要多次执行deploy.sh.
2. 你需要做的就是删掉原来的M3800目录然后重新下载执行.
3. 下载完的目录可以断网执行, 但是不建议你这样做, 因为有可能你会错过很多重要的更新.

---
1. finalstep.sh is no more needed since deploy.sh will finish the whole progress.
2. You have to updated the whole directory by typing

``` sh
git pull
```
1. Once you finish download/update the repository, you can run the deploy.sh without any network connection. But I strongly recommend you not to detach the net because you may miss various important updates.
