### ISSUE TITLE
touchpad not working after sleep

### ISSUE THREAD

**Issue by froggr** [syscl/M3800#19]
Since 4767d00  on May 5th, touchpad stops working after sleep. I see nothing in the logs at all. could it be the change to <key>DisableTPadOnLIDClose</key> in the smarttouch kext?

**Comment by syscl** [comment]
Thanks @froggr , same issue with the newest smarttouchpad kext. 

This issue has nothing to do with the "DisableTPadOnLIDClose" option, because the reason why I changed the "DisableTPadOnLIDClose" option at the 4767d00 is the period I tried to fix the touchpad sleep issue. I'm pretty sure the issue is from v4.6 of smarttouchpad itself but we have no source code to see what's going on! I'll soon revert back to v4.5 which is the best kext for us, with the 3D touch function as well :)

**Comment by syscl** [comment]
Fixed this issue, see 0092f3b. 

syscl

**Comment by froggr** [comment]
Thanks for the fix.
