### ISSUE TITLE
M3800 InjectINTEL wont work

### ISSUE THREAD

**Issue by SaulGoodman1337** [syscl/M3800#26]
Hi,
after exectute the Deploy script the Framebuffer DIE at boot.
Boot without InjectIntel works.
Can you Help me?

M3800 - Patched A10 Bios.
All necessary Bios settings are set.

**Comment by syscl** [comment]
OK, can you provide the screenshot of the execution of deploy.sh. Thx.

syscl

**Comment by SaulGoodman1337** [comment]
Hi,

i've patched IOKit manually. Now it works partially. When OSX booting, the screen is flickering Crazy.
I have made your a Video. 

https://www.youtube.com/watch?v=asXa791-kZA

Have your a Idea?

**Comment by syscl** [comment]
@danielpondruff How's your hardware specification?

**Comment by SaulGoodman1337** [comment]
Display: 3840x2160 with Touch
16 GB Ram
Intel(R) Core(TM) i7-4712HQ

**Comment by syscl** [comment]
OK, @danielpondruff I've just seen the video you made, it seems that you've got 4K model. 

The HD4600 has been powered up, but since OS X doesn't support such resolution with eDP, so we have to inject a smaller resolution for OS X to bypass the black screen issue(flash rate limitation under 4K).

Here's two reference:
1. [Enable-HiDPI](https://github.com/syscl/Enable-HiDPI-OSX)
2. [HiDPI flicker](https://github.com/syscl/M3800/issues/22)

Note: the maximum resolution(HiDPI) you can inject is 1680x945. 1680x945(HiDPI) means (1680*2)x(945*2)=3360x1890.

Wish it could help you.
syscl

**Comment by SaulGoodman1337** [comment]
works !
Thanks

**Comment by syscl** [comment]
@danielpondruff great!!
