### ISSUE TITLE
升级10.11.6

### ISSUE THREAD

**Issue by AKA-KC** [syscl/M3800#34]
用了最新脚本一直卡在安装音频驱动那里就不动了，硬盘读写，显示一直写入20M左右的文件！还有进入系统的时候要在clover界面取消掉注入显卡才能进入

**Comment by syscl** [comment]
再更新一下脚本试一下

我晚些的时候更新到10116

感谢反馈！

**Comment by AKA-KC** [comment]
好的，谢谢回答

**Comment by syscl** [comment]
@KCWong1986 感谢你的反馈，我暂时回退到旧版本了，新的功能暂时移除了，等我修复之后增加!

---

@KCWong1986 Thanks for your feedback, I reverted back to old version of deploy.sh and removed new features temporarily, wait for my fix soon!

syscl

**Comment by syscl** [comment]
@KCWong1986 10.11.6已经测试通过 没有问题。

---

@KCWong1986 10.11.6 has been tested without any issues.

syscl

**Comment by AKA-KC** [comment]
@syscl 好的谢谢.....那我重新升级

**Comment by AKA-KC** [comment]
@syscl 更新10.11.6有睡死的情况出现....你那里有问题么

**Comment by froggr** [comment]
@syscl just as an fyi for anyone updating to 10.11.6, updated to 10.11.6 without seeing the recent issues and also ran latest update which broke high dpi external monitor support (I'm using 2560x1080). Fixed using [mac pixel clock patch v2](https://github.com/Floris497/mac-pixel-clock-patch-V2). I saw pixel clock unlock was temporarily removed from the deploy script due to bugs. 

As a side note, I think it would be helpful to add a note of the current version(s) supported to the readme.

**Comment by syscl** [comment]
@KCWong1986 睡眠我也遇到了一次失败，但是后来没有再遇到过。这个问题我找不到日志. 我已经检测了Azul的二进制，我需要的破解的部分没有发生变动，所以问题应该不在这里。

---

@froggr I re-installed the whole new 10.11.6, and added patch for both 10.12+ and 10.12-. No need to use mac pixel clock patch v2. FYI, the patch of mac pixel clock patch is too complicated and cannot easily be moved into new IOKit/CoreDisplay, so I use a better/more general method to unlock the IOKit/CoreDisplay.

syscl

**Comment by froggr** [comment]
@syscl yes reviewed the commit after I posted that. I have gone back to your method. How is 10.12 support in general? Was thinking of trying on my second machine.

**Comment by syscl** [comment]
@froggr I've tested Sierra PB2 on my M3800, it seems OK. But pay attention to this [issue](https://github.com/vit9696/AppleALC/issues/75). System will hang during the first boot due to a new issue/deadlock issue introduced by Apple in Sierra. Although I removed AppleALC in Sierra, but it seems the issue still stand, I have to update to the latest Sierra to see if Apple has solved this issue. But in general, this issue only cause a very slow boot on my M3800(about 1min) at the first time we cold boot, then it no more occurs until we next cold boot.

I have added Sierra support already, feel free to have a try:)

I will be waiting for your report, thanks!

syscl

**Comment by froggr** [comment]
Install of Sierra PB2 and update to PB4 was smooth and uneventful. I'm experiencing the same boot issues that you mentioned. 

I've only done minimal testing and haven't had time to debug (yet) however immediately notice no bluetooth or wifi. Touchpad performance is odd. Two finger scrolling doesn't work but if you touch along the right of the touchpad you can scroll the page. I assume the touchpad customization isn't working. Otherwise it seems stable at this point. I will do further testing and check the console logs later today. I also notice hfsplus.efi can't be found in the deploy script as I think the file was renamed in a previous commit.

**Comment by syscl** [comment]
@froggr Great to hear that. Please try the latest deploy.sh, I have since fixed some issues and improved the code style.

About Wi-Fi issue you mention above, this problem is caused by the driver not being able to initialize the fvco (frequency voltage controlled oscillator)[credit darkvoid]. Please try this patch:

``` sh
Kext:    AirPortBrcm4360
Find:    81F952AA00007529 
Replace: 81F952AA00006690
```

Through Clover config.plist:

``` sh
<dict>
    <key>Comment</key>
    <string>AirPortBrcm4360 - fcvo</string>
    <key>Disabled</key>
    <false/>
    <key>Find</key>
    <data>gflSqgAAdSk=</data>
    <key>Name</key>
    <string>AirPortBrcm4360</string>
    <key>Replace</key>
    <data>gflSqgAAZpA=</data>
</dict>
```

Since I have since replaced my DW1820 with DW1830(BCM943602), I cannot test such patch. I will be waiting for your report, thanks!

syscl

**Comment by syscl** [comment]
@froggr I have updated the deploy.sh for Sierra to add patches to config.plist accordingly for AppleHDA_ALC668 to power up, try this new update as well.

syscl

**Comment by froggr** [comment]
@syscl thanks and sorry for the delay. The patch worked. Just trying your latest updates as well as upgrading to PB5 and will report back shortly.

**Comment by froggr** [comment]
@syscl after latest deploy.sh update on Sierra PB4 here are my observations:
- wifi working (DW1820) w/ provided Darkvoid rvco patch
- sleep/resume working
- sound (mic, headphones, speakers) working but same issues at 10.11 (i.e. boot with headphone plugged in etc)
-  bluetooth (detecting devices however have yet to test pairing)
- trackpad pref pane in system preferences not working (issue in beta?) so no two finger scroll or multi-touch settings
- no issues with connecting to iCloud etc.
- Will test connecting to highDPI monitor when back in the office on Monday
- function keys not working (i.e. sound, media controls, brightness etc)

Will now update to sierra PB5 and test.

**Comment by froggr** [comment]
@syscl Sierra PB5 works fine. Update was uneventful and required rerunning of deploy script as expected. Not changes to observations above. 

However, touchscreen seems to register as right click and is unusable. Sierra PB5 seems far more stable.

**Comment by syscl** [comment]
@froggr great to hear that, I am so happy that all the patches on Sierra seems work flawlessly, nice!

Another great news is that DW1820 can be powered up(since it can't be correctly initialised under PB2, PB1 and DB1. If you remove the fcvo patch, do the DW1820 work? Since I think Apple has fixed the DW1820(BCM94350 the same as new MacBook 12") initialised issue.

Do the deadlock issue still occurs at the first cold boot(in PB5 or PB4)?

About the touchscreen, how about in 10.11?

About touchpad issue, there's an very odd way to fix the pref issue, that is:
- Remove ApplePS2SmartTouchPad.kext first
- Install the latest [VoodooPS2.kext](https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads)
- Reboot
- Open TouchPad Pref to see if it works
- Remove VoodooPS2.kext and install ApplePS2SmartTouchPad.kext again in Clover/kext/10.12
  I've used this way to fixed this odd issue. Wish it works on your system at this period(I have posted issue to ApplePS2SmartTouchPad's author already, so don't worried ;))

Again, thanks for your valuable and detailed feedback;)
syscl

**Comment by froggr** [comment]
@syscl I removed the fcvo patch but the DW1820 wouldn't fire up unfortunately. 

I'll try the touchpad fix you suggested and report back.

No more issues with cold booting. I had issues in PB3 but not since the upgrade to PB4.

The touchscreen worked perfectly in 10.11 but hasn't worked properly at all in any of the Sierra betas. Always seems that its detecting multitouch.

Any ideas regarding getting the function keys to work (ie brightness, sound etc)?

**Comment by syscl** [comment]
@froggr 
I have updated [SmartTouchPad](https://github.com/syscl/M3800/commit/35853be8f48c4936260d379c97148c62c6aea83e) for Sierra, use the latest one to see if the issue fixed as the author said.

BTW, there's some more functions and modifications I made for SmartTouchPad(more Apple-like), you can try to explore it since I am still very busy these days.

Wish y'all love it.
syscl

**Comment by syscl** [comment]
@KCWong1986 Please try the 10.12.1 from App Store, all function keys have been fixed!
