### ISSUE TITLE
10.11.6

### ISSUE THREAD

**Issue by ghost** [syscl/M3800#38]
On my XPS 9530 (4K) I had the pleasure of re-installing OS X 10.11.5 and 10.11.6 for uncountable times in order to perfect my installation. So far I got the following not working:
- The jack (headphones thing) is not working anymore. It gives a nasty sound like there is a alien in my computer. The sound works without anything plugged in
- The only retina resolution I can use is 1680x945 (Above that will continuously flicker the screen and makes it unable to work with it)
- When using the mini display port or hdmi port (or both) the colours and tramnsparacnty of the OS is really messed up, has that anything todo with the issue above?

The following BIOS settings have been adjusted and patched with the Deploy.sh tool:
- Aperture Size = 512MB
- DVMT Pre-Allocated = 160MB
- DVMT Total Gfx Mem = MAX

I really hope you have a solution for these problems as nobody else seems to be able to help me out.

**Comment by syscl** [comment]
No such issues as you mention above in my M3800(QHD+) under 10.11.6, I was wondering some configurations have not been setup correctly yet. 

But at first, let me answer the questions you pointed out:
- Headphone(HP)

1) This is very possible that the CodecCommander.kext(CC) cannot be injected by Clover, if that is the case, move the CC to `/L*/E*` or `/S*/L*/E*` and rebuild kernel cache by typing

``` sh
sudo touch /S*/L*/E* && sudo touch /L*/E* && sudo kextcache -u /
```

2) The second possibility which causes your HP full of white noise is the latest version of CC fail to init Node number for you. So, try to revert to older version of CC(like `v2.5.1`, see [here](https://github.com/syscl/M3800/commit/c3e905e22474fbd1e8f22d670c15e10a3e0a2884))
3) Some software triggered the white noise, such as, once you open SysPref-->Sound-->Output, then your HP will behave weird as you mention. That's a minor bug in M3800, but since we barely open SysPref-->Sound-->Output and this issue can be solved by simply reboot or sleep the OS X/macOS. Need a further explore in future.
3) Still not work? Please let me know.
- Resolution limitation

This is due to Apple's design, who sets resolution limitation on 4K display with Intel graphics card. Since till now, there's no 4K model available in Macbook with Intel graphics. But, I think  1680x945(HiDPI) is good enough for M3800(4K model). Because, suppose 1920x1080(HiDPI) can be powered up on OS X, along with HD4600, your graphics performance will be dropped down significantly as well as the battery life. The higher resolution you set, the higher pressure you put on GPU. 

BTW, which way do you use to set resolution = 1680x945(HiDPI)? Do you use my [method](https://github.com/syscl/Enable-HiDPI-OSX)? @ssmith353 has reported the method works in [here](https://github.com/syscl/M3800/issues/22). I want to merge that project into deploy.sh to inject the HiDPI resolutions. So can you please provide how many resolutions you can select under Windows(Omit those greater than 1680x945(HiDPI) = 3360x1890)?
- HDMI/DP

1) Do you re-execute deploy.sh?
2) Try rebuild kernel cache by

``` sh
~/M3800/tools/rebuild
```

Or rebuild it by the method I mention above in HP section (1)

3) Can you please provide your ioreg by this [method](http://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/). I have to see what's going on your laptop and then give a correct KextsToPatch for AppleIntelAzulFramebuffer.kext for you. 

Yating/lighting/syscl

**Comment by RicardoJ** [comment]
Thank you for the post. I had to format the laptop and did get back to Windows since the updates and the custom work took me way too mutch time. Thank you for the effort.
