### ISSUE TITLE
10.11.6 睡眠唤醒无声

### ISSUE THREAD

**Issue by LynnTong** [syscl/M3800#41]
codecommander难道没有发挥作用？

**Comment by syscl** [comment]
1. Please at least provide detail information about what you have configured, which version of bootloader you used, which kexts you loaded and so on, otherwise no one can help you.
2. Please follow what exactly the guide says, otherwise, I cannot help you.
3. forger, and a friend in Penn with 1080p model and I have proved that this script has no issues on both 10.11.6 and 10.12, you must have done something wrong.
4. I will allow it once and close it.

---
1. 请提供详细的反馈信息，你这样一句话，没人能帮到你。
2. 请完全按照Github上面的指引操作，否则我无能为力。
3. froggr，宾大1080p的朋友 以及我自己都已经在10.11.6和10.12上面测试过没有问题 有的甚至全新安装。所以仔细检查，你肯定有不正确的操作在这个过程里面。
4. Issues中不接受任何信息都没有的问题.

syscl
