### ISSUE TITLE
Clover don't show OSX "Install Partition" after prepare Sierra ugrade

### ISSUE THREAD

**Issue by SaulGoodman1337** [syscl/M3800#42]
Hi,

Step 1: Load Sierra Update from Appstore
Step 2: Open Setup and let prepare the Installation.
Step 3: Reboot and start OSX Install.

If i reboot, Clover will not show the Sierra Setup, and El Capitan starts normaly.
What did a wrong?

Greetings Daniel

**Comment by syscl** [comment]
@danielpondruff 

Hi, the best way to install a brand new generation operating system(no matter Windows, Linux or macOS) is to install it directly instead of updating from previous version. 

So I strongly recommend you to build a new USB install partition and then install Sierra.

Till now, there may be some change in Sierra so that we cannot easily update from AppStore. Maybe Clover will fix this issue.

syscl
