### ISSUE TITLE
M3800

### ISSUE THREAD

**Issue by tabletka99** [syscl/M3800#46]
Heyas i try u repo at my Dell m3800. Have a some truble.
Toch screen not working, 
Nvidia not working to.
Then battery if i use windows my work time 5h+ in MacOS 2h maximum. why such a big difference?
Then i find https://github.com/ammulder/AppleIntelWiFiMVM wifi 7260 what u thing?

**Comment by SaulGoodman1337** [comment]
Learn to read!
Nvidia Optimus does not work with OSX!
IntelWifi -> This driver is still in the "can it be done?" stage.

**Comment by syscl** [comment]
@tabletka99 You did really mess up something in your computer. In my M3800(QHD+), battery life is longer than 2hours. One post from AustimSMU, he has 5+ hours, you can search it from insanelymac yourself.

Since Apple do not use Optimus, it's temporally impossible to implement such function recently.

About Intel WiFi: it's a great start though. But, still unfinished. I am happy to see if he can finish the project, but he hasn't update his git for 8 months.

The problem of all your questions is that you read guides/reference too little but question/want quite a lot.

syscl

**Comment by syscl** [comment]
@danielpondruff He read quite little but question/want quite a lot, LOL.
